kind: pipeline
name: default

steps:

- name: unit-test
  image: tryffel/virtualpaper-drone:latest
  volumes:
  - name: go-deps
    path: /go
  commands:
  - make ci-test-unit

- name: init-api-tests
  image: tryffel/virtualpaper-drone:latest
  environment:
    VIRTUALPAPER_API_STATIC_CONTENT_PATH: "/app/frontend"
    VIRTUALPAPER_PROCESSING_DATA_DIR: "/data"
    VIRTUALPAPER_PROCESSING_INPUT_DIR: "/input"
    VIRTUALPAPER_LOGGING_DIRECTORY: "/log"
    VIRTUALPAPER_PROCESSING_PANDOC_BIN: "/pandoc-2.18/bin/pandoc"
    VIRTUALPAPER_PROCESSING_PDFTOTEXT_BIN: "/usr/bin/pdftotext"
    VIRTUALPAPER_PROCESSING_IMAGICK_BIN: "/usr/bin/convert"
    VIRTUALPAPER_PROCESSING_TESSERACT_BIN: "/usr/bin/tesseract"
    VIRTUALPAPER_MEILISEARCH_URL: "http://meilisearch:7700"
    VIRTUALPAPER_DATABASE_HOST: postgres
    VIRTUALPAPER_DATABASE_PASSWORD: virtualpaper
    VIRTUALPAPER_DATABASE_DATABASE: virtualpaper
    VIRTUALPAPER_DATABASE_USERNAME: virtualpaper
    VIRTUALPAPER_DATABASE_NO_SSL: true
    VIRTUALPAPER_API_HOST: 0.0.0.0
    VIRTUALPAPER_LOGGING_LOG_LEVEL: DEBUG
  volumes:
  - name: go-deps
    path: /go
  depends_on:
    - unit-test
  commands:
    #- make ci-test-unit
  - go run . migrate --config config.sample.toml
  - go run . manage --config config.sample.toml add-user -U user -P user -a false
  - go run . manage --config config.sample.toml add-user -U admin -P admin -a true

- name: server
  image: tryffel/virtualpaper-drone:latest
  detach: true
  environment:
    VIRTUALPAPER_API_STATIC_CONTENT_PATH: "/app/frontend"
    VIRTUALPAPER_PROCESSING_DATA_DIR: "/data"
    VIRTUALPAPER_PROCESSING_INPUT_DIR: "/input"
    VIRTUALPAPER_LOGGING_DIRECTORY: "/log"
    VIRTUALPAPER_PROCESSING_PANDOC_BIN: "/pandoc-2.18/bin/pandoc"
    VIRTUALPAPER_PROCESSING_PDFTOTEXT_BIN: "/usr/bin/pdftotext"
    VIRTUALPAPER_PROCESSING_IMAGICK_BIN: "/usr/bin/convert"
    VIRTUALPAPER_PROCESSING_TESSERACT_BIN: "/usr/bin/tesseract"
    VIRTUALPAPER_MEILISEARCH_URL: "http://meilisearch:7700"
    VIRTUALPAPER_DATABASE_HOST: postgres
    VIRTUALPAPER_DATABASE_PASSWORD: virtualpaper
    VIRTUALPAPER_DATABASE_DATABASE: virtualpaper
    VIRTUALPAPER_DATABASE_USERNAME: virtualpaper
    VIRTUALPAPER_DATABASE_NO_SSL: true
    VIRTUALPAPER_API_HOST: 0.0.0.0
    VIRTUALPAPER_LOGGING_LOG_LEVEL: DEBUG
  volumes:
  - name: go-deps
    path: /go
  depends_on:
    - unit-test
    - init-api-tests
  commands:
    #- make ci-test-unit
  - go run . serve --config config.sample.toml

- name: api-tests
  image: tryffel/virtualpaper-drone:latest
  environment:
    VIRTUALPAPER_API_STATIC_CONTENT_PATH: "/app/frontend"
    VIRTUALPAPER_PROCESSING_DATA_DIR: "/data"
    VIRTUALPAPER_PROCESSING_INPUT_DIR: "/input"
    VIRTUALPAPER_LOGGING_DIRECTORY: "/log"
    VIRTUALPAPER_PROCESSING_PANDOC_BIN: "/pandoc-2.18/bin/pandoc"
    VIRTUALPAPER_PROCESSING_PDFTOTEXT_BIN: "/usr/bin/pdftotext"
    VIRTUALPAPER_PROCESSING_IMAGICK_BIN: "/usr/bin/convert"
    VIRTUALPAPER_PROCESSING_TESSERACT_BIN: "/usr/bin/tesseract"
    VIRTUALPAPER_MEILISEARCH_URL: "http://meilisearch:7700"
    VIRTUALPAPER_DATABASE_HOST: postgres
    VIRTUALPAPER_DATABASE_PASSWORD: virtualpaper
    VIRTUALPAPER_DATABASE_DATABASE: virtualpaper
    VIRTUALPAPER_DATABASE_USERNAME: virtualpaper
    VIRTUALPAPER_DATABASE_NO_SSL: true
    VIRTUALPAPER_API_HOST: 0.0.0.0
    VIRTUALPAPER_LOGGING_LOG_LEVEL: DEBUG
    VIRTUALPAPER_SERVER_URL: "http://server:8000"
    VIRTUALPAPER_MEILISEARCH_HOST: "http://server:8000"
  depends_on:
    - server
  commands:
    - mkdir frontend/build
    - echo "empty" > frontend/build/gitignore.html
    - sleep 10
    - make ci-test-api
  volumes:
  - name: go-deps
    path: /go


- name: publish
  image: plugins/docker
    #depends_on:
    #api-tests
  settings:
    username: 
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: 
      from_secret: REGISTRY_REPO
    auto_tag: true


services:
- name: meilisearch
  image: getmeili/meilisearch:v0.25.2
    #environment:

- name: postgres
  image: postgres:14.2-alpine3.15
  environment:
    POSTGRES_USER: virtualpaper
    POSTGRES_PASSWORD: virtualpaper
    POSTGRES_DB: virtualpaper

volumes:
- name: go-deps
  temp: {}


