kind: pipeline
name: default

steps:

- name: publish
  image: plugins/docker
    #depends_on:
    #api-tests
  settings:
    username: 
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    repo: 
      from_secret: REGISTRY_REPO
    tags:
    - latest


services:
- name: meilisearch
  image: getmeili/meilisearch:v0.25.2
    #environment:

- name: postgres
  image: postgres:14.2-alpine3.15
  environment:
    POSTGRES_USER: virtualpaper
    POSTGRES_PASSWORD: virtualpaper
    POSTGRES_DB: virtualpaper

volumes:
- name: go-deps
  temp: {}


